### ISSUE TITLE
`cfn test` uses credentials from `~/.aws/credentials` but ignores the region setting.

### ISSUE THREAD

**Issue by brandon-huang-85** [aws-cloudformation/cloudformation-cli#691] opened 2021-02-23 00:29 UTC
A typical entry in `~/.aws/credentials` file looks like this:

```
[my-aws-profile]
aws_access_key_id = <key>
aws_secret_access_key = <key>
region = us-west-2
```

The [documentation](https://docs.aws.amazon.com/cloudformation-cli/latest/userguide/resource-type-cli-test.html#resource-type-cli-test-options) for `cfn test` says:

> If you do not specify an execution role, the contract tests use the environment credentials or the credentials specified in the Boto 3 credentials chain.

Since the credentials can be pulled from the credentials chain, I assumed the region would also be pulled from the same chain. However, it seems the CLI actually only allows 1 of the following: a) set the region explicitly using `--region` argument, or b) default to us-east-1. Thus I was having this error when running contract tests and couldn't figure out why:

```
Resource schema is valid.
Override file invalid: {'ContractTestSnsTopicArn', 'ContractTestExecutionRoleArn'} are not valid cloudformation exports.No Overrides will be applied
```

Obviously since the region was wrong, the CLI was looking for exports in us-east-1, while I'd created them in us-west-2.

I think this is very confusing behavior. It doesn't make sense for the credentials but NOT the region to come from `~/.aws/credentials`. I think this could be remedied by one or more of the following:
- If `--region` override is not explicitly given, search for the region in `~/.aws/credentials` (it can be not set, potentially)
- Instead of defaulting to `us-east-1` silently when a region isn't provided, throw a validation error
- At minimum, produce some kind of log message indicating which region will be used for the contract test.

**Comment by PatMyron** [comment] 2021-02-23 18:22
duplicate of https://github.com/aws-cloudformation/cloudformation-cli/issues/625

**Comment by jotompki** [comment] 2021-02-23 18:23
Default region being set here: https://github.com/aws-cloudformation/cloudformation-cli/blob/master/src/rpdk/core/test.py#L286

**Closed** 2021-03-12 18:37 UTC
