### ISSUE TITLE
Error doing `cfn-cli generate`: "socket.timeout: The read operation timed out"

### ISSUE THREAD

**Issue by miparnisari** [aws-cloudformation/cloudformation-cli#422] opened 2020-04-24 00:00 UTC
```
[2020-04-23T23:59:31Z] DEBUG    - Running generate: Namespace(command=<function generate at 0x102066790>, subparser_name='generate', verbose=0, version=False)
[2020-04-23T23:59:31Z] DEBUG    - Root directory: /Users/mparnisa/workspace-sync/aws-cloudformation-resource-providers-logs/aws-logs-loggroup
[2020-04-23T23:59:31Z] DEBUG    - Loading project file '/Users/mparnisa/workspace-sync/aws-cloudformation-resource-providers-logs/aws-logs-loggroup/.rpdk-config'
[2020-04-23T23:59:31Z] INFO     - Validating your resource specification...
[2020-04-23T23:59:41Z] DEBUG    - Unhandled exception
Traceback (most recent call last):
  File "/Users/mparnisa/Library/Python/3.8/lib/python/site-packages/urllib3/connectionpool.py", line 421, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/Users/mparnisa/Library/Python/3.8/lib/python/site-packages/urllib3/connectionpool.py", line 416, in _make_request
    httplib_response = conn.getresponse()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/http/client.py", line 1322, in getresponse
    response.begin()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/http/client.py", line 303, in begin
    version, status, reason = self._read_status()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/http/client.py", line 264, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/socket.py", line 669, in readinto
    return self._sock.recv_into(b)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/ssl.py", line 1241, in recv_into
    return self.read(nbytes, buffer)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/ssl.py", line 1099, in read
    return self._sslobj.read(len, buffer)
socket.timeout: The read operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/Users/mparnisa/Library/Python/3.8/lib/python/site-packages/urllib3/connectionpool.py", line 719, in urlopen
    retries = retries.increment(
  File "/Users/mparnisa/Library/Python/3.8/lib/python/site-packages/urllib3/util/retry.py", line 400, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/Users/mparnisa/Library/Python/3.8/lib/python/site-packages/urllib3/packages/six.py", line 735, in reraise
    raise value
  File "/Users/mparnisa/Library/Python/3.8/lib/python/site-packages/urllib3/connectionpool.py", line 665, in urlopen
    httplib_response = self._make_request(
  File "/Users/mparnisa/Library/Python/3.8/lib/python/site-packages/urllib3/connectionpool.py", line 423, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "/Users/mparnisa/Library/Python/3.8/lib/python/site-packages/urllib3/connectionpool.py", line 330, in _raise_timeout
    raise ReadTimeoutError(
urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='json-schema.org', port=443): Read timed out. (read timeout=10)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/mparnisa/Library/Python/3.8/lib/python/site-packages/jsonschema/validators.py", line 777, in resolve_from_url
    document = self.resolve_remote(url)
  File "/Users/mparnisa/Library/Python/3.8/lib/python/site-packages/jsonschema/validators.py", line 856, in resolve_remote
    result = self.handlers[scheme](uri)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/rpdk/core/data_loaders.py", line 60, in get_with_timeout
    return requests.get(uri, timeout=timeout).json()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/requests/api.py", line 76, in get
    return request('get', url, params=params, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/requests/sessions.py", line 530, in request
    resp = self.send(prep, **send_kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/requests/sessions.py", line 643, in send
    r = adapter.send(request, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/requests/adapters.py", line 529, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='json-schema.org', port=443): Read timed out. (read timeout=10)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/rpdk/core/cli.py", line 98, in main
    args.command(args)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/rpdk/core/generate.py", line 14, in generate
    project.load()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/rpdk/core/project.py", line 283, in load
    self.load_schema()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/rpdk/core/project.py", line 201, in load_schema
    self.schema = load_resource_spec(f)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/rpdk/core/data_loaders.py", line 102, in load_resource_spec
    validator.validate(resource_spec)
  File "/Users/mparnisa/Library/Python/3.8/lib/python/site-packages/jsonschema/validators.py", line 352, in validate
    for error in self.iter_errors(*args, **kwargs):
  File "/Users/mparnisa/Library/Python/3.8/lib/python/site-packages/jsonschema/validators.py", line 328, in iter_errors
    for error in errors:
  File "/Users/mparnisa/Library/Python/3.8/lib/python/site-packages/jsonschema/_validators.py", line 282, in properties
    for error in validator.descend(
  File "/Users/mparnisa/Library/Python/3.8/lib/python/site-packages/jsonschema/validators.py", line 344, in descend
    for error in self.iter_errors(instance, schema):
  File "/Users/mparnisa/Library/Python/3.8/lib/python/site-packages/jsonschema/validators.py", line 328, in iter_errors
    for error in errors:
  File "/Users/mparnisa/Library/Python/3.8/lib/python/site-packages/jsonschema/_validators.py", line 259, in ref
    scope, resolved = validator.resolver.resolve(ref)
  File "/Users/mparnisa/Library/Python/3.8/lib/python/site-packages/jsonschema/validators.py", line 766, in resolve
    return url, self._remote_cache(url)
  File "/Users/mparnisa/Library/Python/3.8/lib/python/site-packages/jsonschema/validators.py", line 779, in resolve_from_url
    raise exceptions.RefResolutionError(exc)
jsonschema.exceptions.RefResolutionError: HTTPSConnectionPool(host='json-schema.org', port=443): Read timed out. (read timeout=10)
[2020-04-23T23:59:46Z] DEBUG    - Logging set up successfully
[2020-04-23T23:59:46Z] DEBUG    - Running generate: Namespace(command=<function generate at 0x1059bd790>, subparser_name='generate', verbose=0, version=False)
[2020-04-23T23:59:46Z] DEBUG    - Root directory: /Users/mparnisa/workspace-sync/aws-cloudformation-resource-providers-logs/aws-logs-loggroup
[2020-04-23T23:59:46Z] DEBUG    - Loading project file '/Users/mparnisa/workspace-sync/aws-cloudformation-resource-providers-logs/aws-logs-loggroup/.rpdk-config'
[2020-04-23T23:59:46Z] INFO     - Validating your resource specification...
[2020-04-23T23:59:46Z] DEBUG    - Rewriting refs in '<BASE>' (file:///Users/mparnisa/workspace-sync/aws-cloudformation-resource-providers-logs/aws-logs-loggroup/aws-logs-loggroup.json)
[2020-04-23T23:59:46Z] DEBUG    - Writing Resource Role CloudFormation template: /Users/mparnisa/workspace-sync/aws-cloudformation-resource-providers-logs/aws-logs-loggroup/resource-role.yaml
[2020-04-23T23:59:46Z] DEBUG    - Overwriting '/Users/mparnisa/workspace-sync/aws-cloudformation-resource-providers-logs/aws-logs-loggroup/resource-role.yaml'
[2020-04-23T23:59:46Z] DEBUG    - Generate started
[2020-04-23T23:59:46Z] DEBUG    - Removing generated sources: /Users/mparnisa/workspace-sync/aws-cloudformation-resource-providers-logs/aws-logs-loggroup/target/generated-sources/rpdk
[2020-04-23T23:59:46Z] DEBUG    - Removing generated tests: /Users/mparnisa/workspace-sync/aws-cloudformation-resource-providers-logs/aws-logs-loggroup/target/generated-test-sources/rpdk
[2020-04-23T23:59:46Z] DEBUG    - Making generated folder structure: /Users/mparnisa/workspace-sync/aws-cloudformation-resource-providers-logs/aws-logs-loggroup/target/generated-sources/rpdk/software/amazon/logs/loggroup
[2020-04-23T23:59:46Z] DEBUG    - Making generated tests folder structure: /Users/mparnisa/workspace-sync/aws-cloudformation-resource-providers-logs/aws-logs-loggroup/target/generated-test-sources/rpdk/software/amazon/logs/loggroup
[2020-04-23T23:59:46Z] DEBUG    - Writing handler wrapper: /Users/mparnisa/workspace-sync/aws-cloudformation-resource-providers-logs/aws-logs-loggroup/target/generated-sources/rpdk/software/amazon/logs/loggroup/HandlerWrapper.java
[2020-04-23T23:59:46Z] DEBUG    - Overwriting '/Users/mparnisa/workspace-sync/aws-cloudformation-resource-providers-logs/aws-logs-loggroup/target/generated-sources/rpdk/software/amazon/logs/loggroup/HandlerWrapper.java'
[2020-04-23T23:59:46Z] DEBUG    - Writing base configuration: /Users/mparnisa/workspace-sync/aws-cloudformation-resource-providers-logs/aws-logs-loggroup/target/generated-sources/rpdk/software/amazon/logs/loggroup/BaseConfiguration.java
[2020-04-23T23:59:46Z] DEBUG    - Overwriting '/Users/mparnisa/workspace-sync/aws-cloudformation-resource-providers-logs/aws-logs-loggroup/target/generated-sources/rpdk/software/amazon/logs/loggroup/BaseConfiguration.java'
[2020-04-23T23:59:46Z] DEBUG    - Writing base handler: /Users/mparnisa/workspace-sync/aws-cloudformation-resource-providers-logs/aws-logs-loggroup/target/generated-sources/rpdk/software/amazon/logs/loggroup/BaseHandler.java
[2020-04-23T23:59:46Z] DEBUG    - Overwriting '/Users/mparnisa/workspace-sync/aws-cloudformation-resource-providers-logs/aws-logs-loggroup/target/generated-sources/rpdk/software/amazon/logs/loggroup/BaseHandler.java'
[2020-04-23T23:59:46Z] DEBUG    - Writing 1 POJOs
[2020-04-23T23:59:46Z] DEBUG    - ResourceModel POJO: /Users/mparnisa/workspace-sync/aws-cloudformation-resource-providers-logs/aws-logs-loggroup/target/generated-sources/rpdk/software/amazon/logs/loggroup/ResourceModel.java
[2020-04-23T23:59:46Z] DEBUG    - Overwriting '/Users/mparnisa/workspace-sync/aws-cloudformation-resource-providers-logs/aws-logs-loggroup/target/generated-sources/rpdk/software/amazon/logs/loggroup/ResourceModel.java'
[2020-04-23T23:59:46Z] DEBUG    - Generate complete
[2020-04-23T23:59:46Z] WARNING  - Generated files for AWS::Logs::LogGroup
[2020-04-23T23:59:46Z] DEBUG    - Finished generate
```

**Comment by jotompki** [comment] 2020-04-24 00:52
Curious if it has to do with https://github.com/aws-cloudformation/cloudformation-cli/blob/master/src/rpdk/core/data/schema/provider.definition.schema.v1.json#L2

and the [related PR in the resource schema](https://github.com/aws-cloudformation/aws-cloudformation-resource-schema/pull/84) not being ported over

**Comment by wbingli** [comment] 2020-04-28 16:48
Duplicate of #228

**Closed by wbingli** 2020-04-28 16:48 UTC
