### ISSUE TITLE
Update Contract test input payload should not have values from Create Output. Assertion failures for AWS::Redshift::Cluster 

### ISSUE THREAD

**Issue by shwetayakkali** [aws-cloudformation/cloudformation-cli#626] opened 2020-11-12 00:26 UTC
Facing issue with update contract tests. After a read on successful resource creation, the input parameters being passed to the Update Handler are expected to have a null value (if a parameter is not present in input payload to update Handler) but looks like the create handler output is combined with the input payload.

Example : create returns params {A = "a", B= "b", C="c")
input to update = {A="a", B= "bb"}

input being passed to Update Handler = {A="a", B= "bb, C="c"}

expected input passed to Update Handler= {A="a", B= "bb, C="null"}

**Comment by anshikg** [comment] 2020-11-12 00:51
Hi shwetayakkali,
This is expected behavior in update. Because, we dont have a good mechanism to fetch the ReadOnly properties in update we merged the created resource with the inputs_update.json file. This allows us to fetch this property. Is this causing contract test failures?

**Comment by prerna-p** [comment] 2020-11-12 01:23
Why is C="c" being set at all?
Update test will first create a resource and then update it with the properties from inputs_#_update.json.

**Comment by anshikg** [comment] 2020-11-12 01:26
> Why is C="c" being set at all?
> Update test will first create a resource and then update it with the properties from inputs_#_update.json.

thats not true Prerna. We merge the created model with the inputs_#_update.json file: https://github.com/aws-cloudformation/cloudformation-cli/blob/master/src/rpdk/core/contract/resource_client.py#L271

**Comment by prerna-p** [comment] 2020-11-12 01:32
> > Why is C="c" being set at all?
> > Update test will first create a resource and then update it with the properties from inputs_#_update.json.
> 
> thats not true Prerna. We merge the created model with the inputs_#_update.json file: https://github.com/aws-cloudformation/cloudformation-cli/blob/master/src/rpdk/core/contract/resource_client.py#L271

my confusion is why C="c" is passed in inputs_#_ create.json if it is required as null for the update call.

**Comment by shwetayakkali** [comment] 2020-11-12 02:11
> Hi shwetayakkali,
> This is expected behavior in update. Because, we dont have a good mechanism to fetch the ReadOnly properties in update we merged the created resource with the inputs_update.json file. This allows us to fetch this property. Is this causing contract test failures?

Yes, I am seeing failures in update contract tests due to this.

**Comment by shwetayakkali** [comment] 2020-11-12 02:12
> > > Why is C="c" being set at all?
> > > Update test will first create a resource and then update it with the properties from inputs_#_update.json.
> > 
> > 
> > thats not true Prerna. We merge the created model with the inputs_#_update.json file: https://github.com/aws-cloudformation/cloudformation-cli/blob/master/src/rpdk/core/contract/resource_client.py#L271
> 
> my confusion is why C="c" is passed in inputs_#_ create.json if it is required as null for the update call.

I believe it is being passed from the read after the resource creation.

**Comment by ammokhov** [comment] 2020-11-12 22:17
@prerna-p @anshikg if primary identifier/additional identifier is read only we should retrieve it from create handler output and inject it into update request. Merging dictionaries could lead to some unforeseen side effects, so we should avoid it; also read only properties are used for GetAtt but not really involved in post requests.

**Comment by shwetayakkali** [comment] 2020-11-13 20:11
@ammokhov  @anshikg 
Guys, is this being worked on? This is essential for publishing my resource since Update contract tests are failing currently.

Is it possible to estimate a timeline on when this is expected to be done ?

**Comment by anshikg** [comment] 2020-11-13 20:24
> @ammokhov @anshikg
> Guys, is this being worked on? This is essential for publishing my resource since Update contract tests are failing currently.
> 
> Is there an estimated timeline on when this is expected to be done ?

Hi @shwetayakkali 
This not actively been worked on. This should get picked up next sprint. For now, as a work around you could get a local copy of the cli and return just the update model in the line of code mentioned above. That will unblock you for publishing.

**Comment by prerna-p** [comment] 2021-01-07 18:43
Fix has been merged, will be available with the next cli release

**Closed by prerna-p** 2021-01-07 18:43 UTC
Labels: contract tests
