### ISSUE TITLE
Handler takes a long time to complete...?

### ISSUE THREAD

**Issue by DasAng** [aws-cloudformation/cloudformation-cli#372] opened 2019-12-18 21:39 UTC
Hi

I have created a resource in Java and successfully implemented it and it is working.
However just to give more context, my custom resource creates a cloudhsm cluster and in the create handler I implement logic to wait for the cluster to be created using callback context as per documentation.
But what I experience is that the Cloudformation resource takes a long time before it reaches the complete state. 
Attached is a cloudwatch log when the create has finished:

![image](https://user-images.githubusercontent.com/5928487/71125026-722d7d80-21e6-11ea-9fbd-9de7ff30bdc9.png)

Notice the last line where the actual resource has been signalled as completed around 22:21 almost 10 minutes after the 22:12....
Why does it writes out twice:

`Record handler progress`

And why does it take so long time for the second line to be written?. I can see that my resource is stuck in progress state until the second line has been written in cloudwatch logs.

The actual cloudhsm cluster only takes 4-6 minutes to complete. So what is it waiting for even when my code has returned success state once the cloudhsm cluster has been created?

**Comment by rjlohan** [comment] 2019-12-19 16:55
Yes this is not expected. Can you expand (or attach) those log lines to show what the payload for the `RecordHandlerProgress` call was? If you've open-sourced your code I could also take a look at that to repro.

**Comment by DasAng** [comment] 2019-12-20 10:22
@rjlohan Here is the expanded log lines:

![image](https://user-images.githubusercontent.com/5928487/71248386-03057580-231b-11ea-8550-67473635673b.png)


Let me try and put the source code out there.

**Comment by jotompki** [comment] 2019-12-20 14:54
The second  recordHandlerProgress appears to be from a different invocation or operation, as the bearerToken value is different. Logs for record handler progress for the same resource instance should have the same bearer token. If you look at your stack events, is the event for the completion of the cluster around the time we record progress (22:12:35)?

Was the stack updated or another stack created around the time of the second event 10 minutes later?

**Comment by jotompki** [comment] 2019-12-20 15:04
What region was this in?

**Comment by rjlohan** [comment] 2019-12-20 17:34
> The second recordHandlerProgress appears to be from a different invocation or operation, as the bearerToken value is different. Logs for record handler progress for the same resource instance should have the same bearer token. If you look at your stack events, is the event for the completion of the cluster around the time we record progress (22:12:35)?
> 
> Was the stack updated or another stack created around the time of the second event 10 minutes later?

This may mean that the logs are winding up in different LogGroups for multiple concurrent invocations for the same type?

**Comment by DasAng** [comment] 2019-12-20 22:33
@jotompki This was in eu-central-1. And yes I also suspected that the logs are being mixed up into the same loggroup.

It looks like the second resource the one for "Instance" in my template finishes around 22:21 and the log gets mixed up with the log for the first resource "Cluster"

**Comment by DasAng** [comment] 2020-01-02 12:41
Here is another example of similar issue happening and why it takes almost 10 minutes before the next resource is being initiated:

The first screenshot is log from the "cluster" resource and I have only shown the relevant part where the cluster returned success state at around 13:24

![cluster-log](https://user-images.githubusercontent.com/5928487/71667335-f2b2b900-2d64-11ea-9f2d-5b3ed7f02ecc.png)

The next screenshot apparently shows that my next resource the hsm instance is being invoked at around 13:28
![instance-log](https://user-images.githubusercontent.com/5928487/71667376-242b8480-2d65-11ea-8115-13bec57e6848.png)


Why does it take 4 extra minutes to wait before invoking my second resource?
And also what is the first log line in the second screenshot doing there?

**Comment by jotompki** [comment] 2020-01-02 19:28
The [RecordHandlerProgress](https://docs.aws.amazon.com/AWSCloudFormation/latest/APIReference/API_RecordHandlerProgress.html) API is used to report progress back to CloudFormation, so the first line is notifying CloudFormation that the handler was invoked and is now IN_PROGRESS.

As for the four minute delay, if you have a stack ARN I'd love to investigate to see what exactly is happening.

**Comment by DasAng** [comment] 2020-01-08 11:48
I have created a new stack only with one resource the "cluster" resource and executed the stack.
The stack arn is:
arn:aws:cloudformation:eu-central-1:544655944495:stack/infra-cloudhsm-test/7f7c8470-320a-11ea-b8a1-0a78571d47e2

The logs shows my handler has returned success at around 12:36

![image](https://user-images.githubusercontent.com/5928487/71975721-f935aa80-3214-11ea-940b-b6541f002bf8.png)

But the cloudformation stacks shows that the stack completed around 12:40

![image](https://user-images.githubusercontent.com/5928487/71975784-1a969680-3215-11ea-9d14-4b600b233e09.png)

**Comment by jotompki** [comment] 2020-01-09 00:13
After looking at the stack, it looks like the delay is caused by our backoff when polling the status of the resource. The length of the backoff is a bug on CloudFormation's side that is currently being addressed

**Comment by DasAng** [comment] 2020-03-05 16:07
@jotompki are there any updates on this issue?

**Comment by jotompki** [comment] 2020-03-05 18:13
Fix should be deployed out. Going to close this out. If you still see the issue feel free to reopen!

**Closed by jotompki** 2020-03-05 18:13 UTC
