### ISSUE TITLE
Contract test contract_delete_list cannot handle scenario that service owned resource

### ISSUE THREAD

**Issue by liyujiel** [aws-cloudformation/cloudformation-cli#549] opened 2020-08-24 07:51 UTC
Hey,

Our team is failing with contract test contract_delete_list due we provide shared customer resource by service.

For example, all accounts will able to view resource A. But for this test it create resource B and in the end, it only check that non resource exist, which cannot fit with our use case.

Let me know if you wanna me clarify something, thanks!
Alex

**Comment by anshikg** [comment] 2020-08-25 21:06
I am unsure what the issue is here. Please provide stack trace from you test run

**Comment by anshikg** [comment] 2021-01-19 16:45
Closing this issue as we have not received any communication. Feel free to open this if there are any further questions

**Closed by anshikg** 2021-01-19 16:45 UTC
Labels: question
